### ISSUE TITLE
sdk directory is empty

### ISSUE THREAD

**Issue by qbikez** [Azure/azure-documentdb-net#17]
Is this where the sources for Microsoft.Azure.Documents.Client nuget should reside? 
The code in /sdk seems to be missing - there is only a readme.txt saying "source code for DocumentDB .NET SDK". 
Is it possible to add the code here?

**Comment by sjwoodard** [comment]
:+1:

**Comment by ryancrawcour** [comment]
it will be added here, at some point.

**Comment by t03apt** [comment]
@ryancrawcour 
I still can't find the source code. Is it still kept in private or can be accessed somewhere else?

**Comment by ryancrawcour** [comment]
It is still not available.

**Comment by t03apt** [comment]
:( I think this issue shouldn't really be closed.
