### ISSUE TITLE
Can't Find Changelog

### ISSUE THREAD

**Issue by serkanpektas** [Azure/azure-documentdb-net#25]
Where can i find the changelog for [Microsoft Azure DocumentDB Client Library 1.1.0](http://www.nuget.org/packages/Microsoft.Azure.DocumentDB/1.1.0)?

Azure Table Storage has a good [changelog](https://github.com/Azure/azure-storage-net/blob/master/changelog.txt) file. That would be great if there would be one for  [azure-documentdb-net](https://github.com/Azure/azure-documentdb-net) repository as well.

/cc @ryancrawcour @arramac

**Comment by ryancrawcour** [comment]
Thanks for the feedback. Storage also have their SDK source on github which we are still missing, for now. 

This is definitely something we will be adding going forward. The next version of the SDK should include this as part of the NuGet package and once our SDK is fully opened up, it will definitely be part of the repo.

**Comment by ryancrawcour** [comment]
If it would help, I could start one right now for 1.1.0.

**Comment by serkanpektas** [comment]
@ryancrawcour thank you. I have already synced up with the latest changes. That would be great to have  changelog next time :+1:

**Comment by serkanpektas** [comment]
@ryancrawcour any update for the changelog? 1.2 SDK has now been released and I can't find the changelog again. I will have to go and compare the new and old assembly to find out the changes as i did it previously.

**Comment by ryancrawcour** [comment]
https://github.com/Azure/azure-documentdb-net/blob/master/sdk/changelog.md

**Comment by serkanpektas** [comment]
@ryancrawcour that's awesome! Thanks

**Comment by ryancrawcour** [comment]
If you can think of a better place to put this, please let us know. I will be adding it to the NuGet package too, but that only helps after you've updated the package.
