### ISSUE TITLE
it doesnt get build for document db client 1.2.0. I think it is wrongly mentioned in package.config

### ISSUE THREAD

**Issue by vishalgoswami** [Azure/azure-documentdb-net#29]

**Comment by vishalgoswami** [comment]
I used - Uninstall-Package Microsoft.Azure.DocumentDB and Install-Package Microsoft.Azure.DocumentDB to each of the projects in sample code to fix this issue.
"Install-Package Microsoft.Azure.DocumentDB" will basically install version 1.1.0 which is currently the published one on nuget.

**Comment by ryancrawcour** [comment]
I assume you mean one of the latest samples, correct? Which one are you trying to run? If it's Order By, then you will have to wait until we publish the 1.2 NuGet package, which should be later this week.

**Comment by ryancrawcour** [comment]
For all samples, other than Order By, you should be able to build against 1.1

**Comment by vishalgoswami** [comment]
its good. just needed to build the project with 1.1
