### ISSUE TITLE
1.2 SDK? there is no 1.2 SDK

### ISSUE THREAD

**Issue by natsby** [Azure/azure-documentdb-net#34]
trying to use these samples but they won't build because they are referencing a NuGet package that is not available. come on. what's the point of publishing samples that do not work.

**Comment by ryancrawcour** [comment]
Apologies for this. We're prep'ing a new release of the SDK and these samples got pushed before the actual SDK. 

All samples (except Order By) will work with the 1.1 SDK. 
Please update your packages.json to point to 1.1.0 and rebuild.

**Comment by ryancrawcour** [comment]
1.2 SDK has now been released.
