### ISSUE TITLE
Error saving ID field containing a forward slash '/' [.NET SDK 1.2.0]

### ISSUE THREAD

**Issue by Dav-id** [Azure/azure-documentdb-net#35]
Currently with version 1.2.0 it is not possible to create documents that contain a forward slash in the ID field. 

In my case I am using the sample DocumentDBRepository<T> class for convenience and passing in the following: 

    await DocumentDBRepository<Supplier>.CreateItemAsync(new ExampleModel{Id = "test/document"}); 

ExampleModel: 

    public class ExampleModel
    {
        [JsonProperty(PropertyName = "id")]
        public String    Id    { get; set; }
    }

In my code I am not catching the error but when I try to edit a document using Azure Document DocumentDB Studio with an ID of "document" to name it "test/document" I get the following: 

     System.ArgumentException: The resource name presented contains invalid character '/'.
        at Microsoft.Azure.Documents.Client.DocumentClient.ValidateResource(Resource resource)
        at           Microsoft.Azure.Documents.Client.DocumentClient.<ReplaceDocumentPrivateAsync>d__f2.MoveNext     ()
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification     (Task task)
        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        at Microsoft.Azure.DocumentDBStudio.DocumentNode.<UpdateNode>d__58.MoveNext() in      f:\git\DocumentDB-studio\DocumentDBStudio\TreeNodes.cs:line 1345

Interestingly I am able to edit the document to give it the desired ID when I edit through the Document Explorer within the Azure Portal.

Edit: Just want to add that I have reverted back to version 1.1.0 of the .NET SDK which does not have this particular issue.

**Comment by ryancrawcour** [comment]
This was a necessary change that needed to be put in place for a future feature of the service. 

As you know all resources in DocumentDB are addressable by a URI. In the future this URI will be composed of the IDs you use, not internal hashed IDs it uses today. 

To support this we can't support unescaped unencoded characters such as /, $, ? etc. in ID fields as these are reserved characters in URIs. 

Apologies for not listing this as a breaking change.
I missed it when going through the changelog.

**Comment by ryancrawcour** [comment]
We can release 1.2.1 which removes this constraint and allows your application to continue with the other additions to the SDK. Would this work for you?

**Comment by Dav-id** [comment]
Thank you for your explanation. Knowing it is intended behaviour I am happy to keep it that way rather than a temporary work around that could potentially cause additional work in the future.

Fortunately in my particular case it wont be problematic to update my ID field to remove the slashes and in the interest of being more future proof this is what I will do. 

Thanks
David

**Comment by ryancrawcour** [comment]
Thanks David. Apologies that this slipped through ahead of time.

**Comment by jerfcero** [comment]
try 
Select ....
REPLACE(REPLACE(REPLACE(i.VAL, '?', ' '), '#', ' '), '/', ' ') as [VAL],
others fields
into
..... ComosDB....
from
......
