### ISSUE TITLE
Cannot list a collection created through the portal

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-net#37]
I created a new collection using the azure portal.  When I try to list the available collections within my application I get the following error.

Errors":["The collection 'User1' could not be read because it was created with a newer API version.

According to NuGet I have the latest Microsoft.Azure.DocumentDB library installed (Version 1.1.0)

**Comment by stephbaron** [comment]
You'll need to update to the latest .NET SDK and that will resolve the issue.

**Comment by ryancrawcour** [comment]
1.2 is the latest SDK published on NuGet as per http://www.nuget.org/packages/Microsoft.Azure.DocumentDB/
