### ISSUE TITLE
Many source code links are broken

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-documentdb-net#46]
For instance on page [DocumentDB Partitioning Samples](https://github.com/Azure/azure-documentdb-net/tree/master/samples/code-samples/Partitioning) all links like this:

    https://github.com/Azure/azure-documentdb-net/tree/master/samples/partitioning/DocumentDB.Samples.Sharding/DocumentDB.Samples.Sharding/Partitioners/LookupPartitionResolver.cs

should actually lead to:

    https://github.com/Azure/azure-documentdb-net/blob/master/samples/code-samples/Partitioning/Partitioners/LookupPartitionResolver.cs

**Comment by ryancrawcour** [comment]
This has been fixed with the latest release.
