### ISSUE TITLE
NuGet package restore problem

### ISSUE THREAD

**Issue by scorbiere** [Azure/azure-documentdb-net#53]
Hi,

It seems that with the last version of NuGet,, the simple build and run of the samples does not work anymore.
I solved this problem with the help of this article : http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

Problem found with VS 2013 and 2015.

**Comment by ryancrawcour** [comment]
Thanks for reporting this. It should now be fixed.
