### ISSUE TITLE
Issue with StartsWith query

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-net#59]
Following is a table of results for some queries from the same collection using the portal although I get the same results using my own application with the sdk (1.4.1)

select * from c where c.ObjectType="System.SearchIndexQueueItem"   29.27 RUs 100+ results
 select * from c where c.ObjectType="Document"                                  37.39 RUs 100+ results
   
 select * from c where StartsWith(c.ObjectType,"Doc")                  42.42 RUs 100+ results
 select * from c where StartsWith(c.ObjectType,"Sys")                   1035 RUs shows no results but Has More Results is True

So the last query should return results but does not. I have seen a report elsewhere that someone is having the converse issue (the StartWith works but the equality (=) does not) so there is clearly an issue here.
I can provide further information/screenshots etc if necessary on request). I have attached some screenshots below

![equality](https://cloud.githubusercontent.com/assets/7965853/10220137/d0833400-683c-11e5-8d57-fe268013a771.jpg)
![startswith](https://cloud.githubusercontent.com/assets/7965853/10220142/dd22a8a8-683c-11e5-937f-7fcf589012d7.jpg)
![startswithdoc](https://cloud.githubusercontent.com/assets/7965853/10220219/73ccaa2e-683d-11e5-91e4-9045a1b2e533.jpg)

**Comment by ryancrawcour** [comment]
There are actually two issues at work here. Firstly there is a back-end issue which we're to resolve that might return empty first page with a continuation token saying there are more results. This happens under certain data patterns. The second issue here is that the portal query explorer is not currently honoring this and going off to fetch the results. This will be worked on too. 

I suspect that if you hit "Next page" button, it will display your results.

**Comment by Geetarman** [comment]
OK thanks.
I tried the next page.  If I leave the collection at S1 level then I cannot get it to retrieve the results.  Next page keeps returning no records or "Request rate is large".
I changed the performance level to S3 and managed to get results back after clicking 'Next Page' 4 times but I have to do that slowly as the request rate issue still occurs.

I think it is important to note that when at S1 level the request charge for the first (blank) page is around 1000 RUs.  When I upgrade the collection to S3 level the request charge for the same query jumps to around 7600 RUs.

Additionally, on a different collection I have what appears to be a similar issue
SELECT * FROM c ORDER BY c.StatusCode asc returns blank pages 
SELECT * FROM c ORDER BY c.StatusCode desc works no problem
This is a much more serious issue for me as I am about to implement sorting in our main product.  I am going to try to put a 'hack' into the code to navigate to the first page but I suspect this will perform really poorly because of the high request rate.

If you want access to the data do no hesitate to contact me.
I will not be able to deploy with this issue outstanding.

**Comment by ryancrawcour** [comment]
Will look in RU charge based on performance level.
We may need access to the data for this database to investigate. If possible, email me at ryancraw at microsoft dot com

**Comment by ryancrawcour** [comment]
The issue with StartsWith is because of no range index on the path you are trying to query. Please add a range index to that path. 

Could you please split the "blank pages with Order By" in to a separate issue so we can track that one independently. 

Thanks.
