### ISSUE TITLE
Query ignoring feed options?

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-net#73]
I am not sure if this actually an issue but it is not doing what i expected (hoped).
I use the following code to get the first document based on a query.  I have just imported 1.5 million documents into my system and I find that if I execute this using a query that matches a lot of documents the query looks like it is returning all the documents before returning the FirstOrDefault (because the query is essentially hanging).

var document = client.CreateDocumentQuery(documentsLink, query, MaxOneDocument).AsEnumerable().FirstOrDefault();

private FeedOptions MaxOneDocument  {
     get {   return new FeedOptions() { MaxItemCount = 1 };  }
}

I have an alternative which does work (using .AsDocumentQuery()) so I can change to using that instead but I am interested to know if the above is the correct intended behaviour.

**Comment by ryancrawcour** [comment]
Not sure what the value of query is here but I presume it doesn't have much in the way of filter criteria.

Internally the call to AsEnumerable will go an iterate through all the results MaxItemCount number of items each time until there are no more results. Then it will pick the first one from that and return it to you. 

So in your case it will be making 1.5 million requests to the server to fetch 1 record at a time. You will be able to see this if you open something like Fiddler and watch the requests going to the server. 

If you lift the value for MaxItemCount you will see fewer requests going to the server. A value of -1 for MaxItemCount will tell the server to process as much as it can for a single response. This will ultimately result in the smallest number of roundtrips to the server to fetch all the results.

As you have seen, AsDocumentQuery doesn't behave the same way and will let you control each subsequent trip to the server with the ExecuteNextAsync method.

**Comment by Geetarman** [comment]
I was trying to get the first document and last document using an order by query.  I can see that MaxItemCount is for each request now rather than the total number of documents to bring back.  I was hoping it behaved like select top 1 * from c .....

**Comment by ryancrawcour** [comment]
Yes, Top and MaxItemCount are different. 
Today you can achieve what you are trying to do with AsDocumentQuery and MaxItemCount = 1 Order By XYZ ASC and then reversing the sort order and doing it again. 

Top is being worked on

**Comment by Geetarman** [comment]
Yes I have just implemented exactly that.  Just some confusion on my part and the original method was not async so i didn't want to have to convert it to an async method....

tis all good now thanks
